# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-jekyll:testing"


command:
  update:
    - "git submodule update --init --remote"

  run:
    - "D:jekyll serve -H 0.0.0.0 -s /opt/docs -d /tmp/_build --force_polling"
