title: infracamp.org
description: educational grade development tools
google_analytics:
show_downloads: true
include:
- projects/kickstart
safe: true

plugins:
#- jekyll-mentions
#- jekyll-default-layout