title: infracamp.org
description: educational grade development tools
google_analytics:
show_downloads: true
include:
- projects/kickstart

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: developer camp

plugins:
- jekyll-optional-front-matter